In [ ]:
# just import statement
import numpy as np

In [ ]:
# version
print(np.__version__)
# configuration
print(np.__config__.show())

In [10]:
# create a null vector of size 10
null_vec = np.zeros([10])
print null_vec.shape, null_vec
null_vec1 = np.zeros(10)
print null_vec1.shape, null_vec1

(10,) [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
(10,) [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [12]:
np.info(np.reshape)

 reshape(a, newshape, order='C')

Gives a new shape to an array without changing its data.

Parameters
----------
a : array_like
    Array to be reshaped.
newshape : int or tuple of ints
    The new shape should be compatible with the original shape. If
    an integer, then the result will be a 1-D array of that length.
    One shape dimension can be -1. In this case, the value is inferred
    from the length of the array and remaining dimensions.
order : {'C', 'F', 'A'}, optional
    Read the elements of `a` using this index order, and place the elements
    into the reshaped array using this index order.  'C' means to
    read / write the elements using C-like index order, with the last axis
    index changing fastest, back to the first axis index changing slowest.
    'F' means to read / write the elements using Fortran-like index order,
    with the first index changing fastest, and the last index changing
    slowest.
    Note that the 'C' and 'F' options take no account of the me

In [15]:
# a null vector of size 10, with 5th value as 1
null_vec_2 = np.zeros(10)
null_vec_2[4] = 1
print null_vec_2
# try something similar with 2d array
temp_null_vec = np.zeros([3,3])
print 'before',temp_null_vec
for i in xrange(3):
    temp_null_vec[i,i] = 1
print 'after',temp_null_vec

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
before [[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
after [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [27]:
# create a vector ranging from 10-49
# easy : just use arange
new_vec_10_49 = np.arange(10,50)
print new_vec_10_49
# booom!

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [58]:
# reverse a vector
print new_vec_10_49[::-1]

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [61]:
# create a 3x3 matrix with values 0-8
print np.arange(9).reshape(3,3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [80]:
# get the indices of non-elements
temp_vec_with_zeros  = np.array([1,2,3,0,0,5,0,6])
temp_vec_wo_zeros = np.nonzero(temp_vec_with_zeros)
print 'indices',temp_vec_wo_zeros
print 'elements',temp_vec_with_zeros[temp_vec_wo_zeros]

x = np.eye(3)
print x[np.nonzero(x)]
y = np.array([[1,2,0,4],[1,0,0,1]])
print y[np.nonzero(y)]

indices (array([0, 1, 2, 5, 7]),)
elements [1 2 3 5 6]
[ 1.  1.  1.]
[1 2 4 1 1]


In [85]:
# 3x3 identity matrix
print np.eye(3,3)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [84]:
# create a 3x3x3 array of random values
print np.random.random((3,3,3))
# input param : tuple : shape

[[[ 0.10105726  0.37921995  0.60843009]
  [ 0.50395725  0.37257237  0.76085724]
  [ 0.94342458  0.45740496  0.68632852]]

 [[ 0.283169    0.48092198  0.78233965]
  [ 0.63332415  0.68638271  0.11467733]
  [ 0.4309975   0.45182983  0.60620997]]

 [[ 0.92873858  0.50415258  0.9621811 ]
  [ 0.50257209  0.01814115  0.46214015]
  [ 0.3741058   0.84660411  0.46756382]]]


In [90]:
# create 10x10 array with random values and find the minimum and maximum values
print 'max',np.amax(np.random.random((10,10)))
print 'min',np.amin(np.random.random((10,10)))

max 0.999428312874
min 0.0381272851765


In [96]:
# mean of vector with 30 random elements
print 'mean',np.mean(np.random.random((30,)))
print 'OR : mean',(np.random.random((30,))).mean()

mean 0.469269136754
OR : mean 0.510674440469


In [110]:
# diagonal np.diag
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print x
np.diag(x,1)
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 
y = np.arange(5)
print y
np.diag(y+1,-1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[0 1 2 3 4]


array([[0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0]])

In [114]:
# create a checkerboard pattern in a 8x8 matrix
x = np.zeros((8,8))
x[::2,1::2] = 1
x[1::2,::2] = 1
print x

[[ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]]


In [118]:
# Normalization
x = np.random.random((5,5))
x_norm =  x/(x.sum())
print 'after normalization, sum : ', x_norm.sum()

after normalization, sum :  1.0


In [120]:
# Matrix multiplication
#  5x3 . 3x2
#  Use of dot(x,y)
x = np.random.random((5,3))
y = np.random.random((3,2))
print np.dot(x,y)

[[ 0.8124616   0.47108254]
 [ 0.2613689   0.14206686]
 [ 0.42128995  0.19423467]
 [ 0.84069103  0.48468538]
 [ 0.42905843  0.23228635]]


In [123]:
# 5x5 matrix with row values ranging from 0 to 5
z = np.zeros((5,5))
print z + np.arange(0,5)

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


In [135]:
# a vector of size 10 with values ranging from  0 to 1
x = np.random.random(10)
x = x/x.sum()
# print x

# Suggested : Use of np.linspace() function
print np.linspace(0,1,12)
print np.linspace(0,1,12)[1:-1]

[ 0.          0.09090909  0.18181818  0.27272727  0.36363636  0.45454545
  0.54545455  0.63636364  0.72727273  0.81818182  0.90909091  1.        ]
[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]
