In [ ]:
# just import statement
import numpy as np

In [ ]:
# version
print(np.__version__)
# configuration
print(np.__config__.show())

In [10]:
# create a null vector of size 10
null_vec = np.zeros([10])
print null_vec.shape, null_vec
null_vec1 = np.zeros(10)
print null_vec1.shape, null_vec1

(10,) [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
(10,) [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [12]:
np.info(np.reshape)

 reshape(a, newshape, order='C')

Gives a new shape to an array without changing its data.

Parameters
----------
a : array_like
    Array to be reshaped.
newshape : int or tuple of ints
    The new shape should be compatible with the original shape. If
    an integer, then the result will be a 1-D array of that length.
    One shape dimension can be -1. In this case, the value is inferred
    from the length of the array and remaining dimensions.
order : {'C', 'F', 'A'}, optional
    Read the elements of `a` using this index order, and place the elements
    into the reshaped array using this index order.  'C' means to
    read / write the elements using C-like index order, with the last axis
    index changing fastest, back to the first axis index changing slowest.
    'F' means to read / write the elements using Fortran-like index order,
    with the first index changing fastest, and the last index changing
    slowest.
    Note that the 'C' and 'F' options take no account of the me

In [14]:
# a null vector of size 10, with 5th value as 1
null_vec_2 = np.zeros(10)
null_vec_2[4] = 1
print null_vec_2
# try something similar with 2d array
temp_null_vec = np.zeros([3,3])
print 'before',temp_null_vec
for i in xrange(3):
    temp_null_vec[i,i] = 1
print 'after',temp_null_vec

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
before [[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
after [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
