In [2]:
import numpy as np

In [4]:
# Create dataset
nb_of_samples = 20
sequence_len = 10
# Create the sequences
X = np.zeros((nb_of_samples, sequence_len))
for row_idx in range(nb_of_samples):
    X[row_idx,:] = np.around(np.random.rand(sequence_len)).astype(int)
# Create the targets for each sequence
t = np.sum(X, axis=1)

In [18]:
#print t
print X
# sum of each sequence gives t
X.shape[0]
M = X.shape[0]
print M

[[ 1.  0.  1.  0.  0.  1.  0.  1.  1.  0.]
 [ 0.  1.  0.  1.  1.  0.  0.  1.  0.  1.]
 [ 0.  0.  0.  0.  1.  1.  1.  0.  0.  1.]
 [ 0.  0.  0.  0.  1.  1.  1.  0.  1.  0.]
 [ 1.  0.  1.  1.  1.  0.  1.  1.  1.  0.]
 [ 0.  0.  1.  1.  1.  1.  0.  0.  1.  1.]
 [ 1.  0.  0.  0.  1.  0.  1.  0.  1.  1.]
 [ 1.  1.  1.  0.  0.  0.  0.  1.  0.  1.]
 [ 0.  0.  1.  0.  0.  1.  1.  1.  1.  0.]
 [ 1.  0.  1.  1.  0.  0.  0.  1.  1.  0.]
 [ 1.  1.  0.  1.  0.  0.  0.  1.  1.  0.]
 [ 1.  1.  1.  0.  0.  1.  1.  0.  1.  0.]
 [ 1.  0.  1.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  1.  0.  1.  1.  1.  1.  1.  0.  1.]
 [ 0.  1.  0.  1.  0.  1.  0.  0.  1.  0.]
 [ 0.  1.  0.  0.  1.  1.  1.  0.  1.  0.]
 [ 1.  1.  1.  1.  0.  1.  1.  1.  0.  0.]
 [ 0.  1.  0.  1.  0.  1.  1.  0.  0.  1.]
 [ 0.  1.  1.  0.  0.  1.  0.  1.  1.  1.]
 [ 0.  0.  0.  1.  0.  0.  1.  1.  1.  0.]]
20


In [8]:
def step(xk,sk,Wx,Wrec):
    return (xk*Wx) + (Wrec*sk)    

In [13]:
def forward(X,Wx,Wrec):
    # S : a list of states : n+1 states
    #  given n = X.shape[1] = 10 
    #   also X.shape[0] = 20 (training examples)
    S = np.zeros((X.shape[0], X.shape[1] + 1))
    # iterate through each item in sequence(10), for each batch(size = 20)
    for k in xrange(X.shape[1]):
        S[:,k+1] = step(X[:,k],S[:,k],Wx,Wrec)
    return S

In [17]:
def cost(y,t):
    return ((y-t)**2).sum()/M

In [20]:
def output_gradient(y,t):
    return 2*(y-t)/M

In [46]:
def bwd_gradient(X,S,grad_out,Wrec):
    # accumulate gradient of output w.r.t state in a list
    #grad_state = np.zeros((X.shape[0],Xshape[1]+1))
    grad_state = np.zeros(S.shape)
    # gradient w.r.t of last layer
    grad_state[:,-1] = grad_out
    # init gradient containers for Wx and Wrec
    #  grad_wx, grad_wrec
    grad_wx=0
    grad_wrec=0
    for k in xrange(X.shape[1],0,-1):
        grad_wx += np.sum(grad_state[:,k] * X[:,k-1])
        grad_wrec += np.sum(grad_state[:,k] * S[:,k-1])
        # previous layer gradient 
        grad_state[:,k-1] = grad_state[:,k] * grad_wrec
    return (grad_wx,grad_wrec)#,grad_state

In [26]:
Wx = np.random.uniform()
print Wx
Wrec = np.random.uniform()
print Wrec

0.96139291365
0.311680958476


In [28]:
# get states
S = forward(X,Wx,Wrec)

In [31]:
t

array([ 5.,  5.,  4.,  4.,  7.,  6.,  5.,  5.,  5.,  5.,  5.,  6.,  3.,
        7.,  4.,  5.,  7.,  5.,  6.,  4.])

In [34]:
cost(S[:,-1],t)

21.266034640791226

In [37]:
grad_out = output_gradient(S[:,-1],t)
print grad_out

[-0.45975834 -0.39414177 -0.29975972 -0.36593422 -0.65738377 -0.47259025
 -0.37069954 -0.39448255 -0.45685008 -0.46057748 -0.46059639 -0.5661783
 -0.29063041 -0.59032356 -0.36903123 -0.46592566 -0.6867155  -0.3999458
 -0.46361315 -0.35769669]


In [50]:
bwd_gradient(X,S,grad_out,Wrec)

/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:15: RuntimeWarning: overflow encountered in multiply
/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:12: RuntimeWarning: invalid value encountered in multiply
/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:13: RuntimeWarning: invalid value encountered in multiply


(nan, nan)

In [49]:
grad_wx

nan